services:
  mysql:
    image: mysql:latest
    container_name: mousehunt
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_LOCAL_HOST}:${MYSQL_CONTAINER_PORT}"
    volumes:
      - mh_data:/var/lib/mysql
      - ./mousehunt-db:/docker-entrypoint-initdb.d
    restart: always

volumes:
  mh_data:

